name: Lint with Bun

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write  # Needed for auto-fix on push

jobs:
  check:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Run Prettier Check
        run: bun run format:check src/
      - name: Run ESLint
        run: bun run lint src/

  fix:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Run Prettier Fix
        run: bun run format src/
      - name: Run ESLint Fix
        run: bun run lint:fix src/
      - name: Commit and Push Fixes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/
          git commit -m "Auto-fix formatting and lint issues" || echo "No changes to commit"
          git push
