name: Vale Grammar

on:
  pull_request:
    paths:
      - 'src/content/docs/**/*.md'
      - 'src/content/docs/**/*.mdx'

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Vale Linter
        uses: errata-ai/vale-action@v2.1.1
        with:
          version: 2.28.0
          files: "src/content/docs/**/*.md,src/content/docs/**/*.mdx"
          reporter: github-pr-review
          fail_on_error: false
          level: warning
          filter_mode: diff_context
